let num = 200;
const randomImg = () => {
  num++;
  return "https://picsum.photos/" + num.toString();
};
const Img1 = "https://picsum.photos/200";
const Img2 = "https://picsum.photos/201";

export default dataChat = [
  {
    ID: 1,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Chào bạn, cho mình làm quen.",
    timeSend: "2 ngày trước",
    sender: true,
  },
  {
    ID: 2,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Chào, hình như mình vừa gặp bạn hôm qua",
    timeSend: "hôm qua",
    sender: false,
  },
  {
    ID: 3,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Đúng rồi.",
    timeSend: "23 giờ trước",
    sender: true,
  },
  {
    ID: 4,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Ở đầu đường Lê Văn Việt á.",
    timeSend: "23 giờ trước",
    sender: true,
  },
  {
    ID: 5,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "À, mình nhớ rồi. Bạn có hay đi qua đó không?",
    timeSend: "22 giờ trước",
    sender: false,
  },
  {
    ID: 6,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Ừ, mình hay đi qua đó lắm.",
    timeSend: "21 giờ trước",
    sender: true,
  },
  {
    ID: 7,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Vậy lần sau gặp lại nhé!",
    timeSend: "20 giờ trước",
    sender: false,
  },
  {
    ID: 8,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Ok, hẹn gặp lại bạn.",
    timeSend: "19 giờ trước",
    sender: true,
  },
  {
    ID: 9,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Bạn có hay đi cà phê không?",
    timeSend: "18 giờ trước",
    sender: false,
  },
  {
    ID: 10,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Có chứ, mình rất thích cà phê.",
    timeSend: "17 giờ trước",
    sender: true,
  },
  {
    ID: 11,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Vậy hôm nào mình đi cà phê nhé?",
    timeSend: "16 giờ trước",
    sender: false,
  },
  {
    ID: 12,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Được thôi, bạn rảnh khi nào?",
    timeSend: "15 giờ trước",
    sender: true,
  },
  {
    ID: 13,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Cuối tuần này bạn có rảnh không?",
    timeSend: "14 giờ trước",
    sender: false,
  },
  {
    ID: 14,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Cuối tuần này mình rảnh. Hẹn bạn lúc 3 giờ chiều nhé?",
    timeSend: "13 giờ trước",
    sender: true,
  },
  {
    ID: 15,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Ok, mình sẽ đến đúng giờ.",
    timeSend: "12 giờ trước",
    sender: false,
  },
  {
    ID: 16,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Hẹn gặp bạn.",
    timeSend: "11 giờ trước",
    sender: true,
  },
  {
    ID: 17,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Hẹn gặp lại.",
    timeSend: "10 giờ trước",
    sender: false,
  },
  {
    ID: 18,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Bạn thích uống cà phê gì?",
    timeSend: "9 giờ trước",
    sender: true,
  },
  {
    ID: 19,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Mình thích cà phê sữa đá.",
    timeSend: "8 giờ trước",
    sender: false,
  },
  {
    ID: 20,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Mình cũng thích cà phê sữa đá.",
    timeSend: "7 giờ trước",
    sender: true,
  },
  {
    ID: 21,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Vậy thì tuyệt quá.",
    timeSend: "6 giờ trước",
    sender: false,
  },
  {
    ID: 22,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Bạn có hay đi du lịch không?",
    timeSend: "5 giờ trước",
    sender: true,
  },
  {
    ID: 23,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Có, mình rất thích đi du lịch.",
    timeSend: "4 giờ trước",
    sender: false,
  },
  {
    ID: 24,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Bạn đã đi những đâu rồi?",
    timeSend: "3 giờ trước",
    sender: true,
  },
  {
    ID: 25,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Mình đã đi Đà Lạt, Nha Trang, và Phú Quốc.",
    timeSend: "2 giờ trước",
    sender: false,
  },
  {
    ID: 26,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Wow, bạn đi nhiều nơi quá.",
    timeSend: "1 giờ trước",
    sender: true,
  },
  {
    ID: 27,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Còn bạn thì sao?",
    timeSend: "45 phút trước",
    sender: false,
  },
  {
    ID: 28,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Mình mới đi Đà Nẵng và Huế thôi.",
    timeSend: "30 phút trước",
    sender: true,
  },
  {
    ID: 29,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Đà Nẵng và Huế cũng đẹp lắm.",
    timeSend: "20 phút trước",
    sender: false,
  },
  {
    ID: 30,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Ừ, mình rất thích.",
    timeSend: "15 phút trước",
    sender: true,
  },
  {
    ID: 31,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Bạn có dự định đi đâu nữa không?",
    timeSend: "10 phút trước",
    sender: false,
  },
  {
    ID: 32,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Mình đang dự định đi Sapa vào tháng tới.",
    timeSend: "9 phút trước",
    sender: true,
  },
  {
    ID: 33,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Sapa đẹp lắm, bạn sẽ thích cho mà xem.",
    timeSend: "8 phút trước",
    sender: false,
  },
  {
    ID: 34,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Bạn đã từng đi Sapa chưa?",
    timeSend: "7 phút trước",
    sender: true,
  },
  {
    ID: 35,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Rồi, mình đã đi một lần vào mùa đông.",
    timeSend: "6 phút trước",
    sender: false,
  },
  {
    ID: 36,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Mùa đông ở Sapa chắc đẹp lắm nhỉ?",
    timeSend: "5 phút trước",
    sender: true,
  },
  {
    ID: 37,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Đúng rồi, có tuyết rơi nữa.",
    timeSend: "4 phút trước",
    sender: false,
  },
  {
    ID: 38,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Nghe hấp dẫn quá, mình sẽ chuẩn bị kỹ.",
    timeSend: "3 phút trước",
    sender: true,
  },
  {
    ID: 39,
    userName: "lethib234",
    fulName: "Le Thi B",
    image: Img2,
    latestMessage: "Chúc bạn có chuyến đi vui vẻ nhé!",
    timeSend: "2 phút trước",
    sender: false,
  },
  {
    ID: 40,
    userName: "nguyenvana123",
    fulName: "Nguyen Van A",
    image: Img1,
    latestMessage: "Cảm ơn bạn nhiều!",
    timeSend: "1 phút trước",
    sender: true,
  },
];
