let num = 200;
const randomImg = () => {
  num++;
  return 'https://picsum.photos/' + num.toString();
};
export default dataFriends = [
  {
    ID: 1,
    userName: 'nguyenvana123',
    fulName: 'Nguyen Van A',
    image: randomImg(),
    latestMessage: 'Chào bạn, cho mình làm quen.',
    timeSend: 'hôm qua',
  },
  {
    ID: 2,
    userName: 'lethib234',
    fulName: 'Le Thi B',
    image: randomImg(),
    latestMessage: 'Em học bài chưa?',
    timeSend: '10 giờ trước',
  },
  {
    ID: 3,
    userName: 'trananh345',
    fulName: 'Tran Anh',
    image: randomImg(),
    latestMessage: 'Hôm nay bạn thế nào?',
    timeSend: '5 phút trước',
  },
  {
    ID: 4,
    userName: 'phamthic678',
    fulName: 'Pham Thi C',
    image: randomImg(),
    latestMessage: 'Có hẹn tối nay không?',
    timeSend: '2 giờ trước',
  },
  {
    ID: 5,
    userName: 'dangdinh890',
    fulName: 'Dang Dinh',
    image: randomImg(),
    latestMessage: 'Mình sắp đến rồi nhé!',
    timeSend: '15 phút trước',
  },
  {
    ID: 6,
    userName: 'ngoctran123',
    fulName: 'Ngoc Tran',
    image: randomImg(),
    latestMessage: 'Làm xong bài chưa?',
    timeSend: '3 ngày trước',
  },
  {
    ID: 7,
    userName: 'nguyend456',
    fulName: 'Nguyen D',
    image: randomImg(),
    latestMessage: 'Đi ăn không?',
    timeSend: '30 phút trước',
  },
  {
    ID: 8,
    userName: 'dinhhieu789',
    fulName: 'Dinh Hieu',
    image: randomImg(),
    latestMessage: 'Chúc ngủ ngon!',
    timeSend: '1 giờ trước',
  },
  {
    ID: 9,
    userName: 'kimlien234',
    fulName: 'Kim Lien',
    image: randomImg(),
    latestMessage: 'Mình đang ở quán cà phê, bạn tới không?',
    timeSend: '2 ngày trước',
  },
  {
    ID: 10,
    userName: 'thanhhoa567',
    fulName: 'Thanh Hoa',
    image: randomImg(),
    latestMessage: 'Nhớ nộp bài đúng giờ nhé.',
    timeSend: '5 giờ trước',
  },
  {
    ID: 11,
    userName: 'hoangle123',
    fulName: 'Hoang Le',
    image: randomImg(),
    latestMessage: 'Có ai online không?',
    timeSend: '10 phút trước',
  },
  {
    ID: 12,
    userName: 'minhanh345',
    fulName: 'Minh Anh',
    image: randomImg(),
    latestMessage: 'Đi học thêm không?',
    timeSend: '4 giờ trước',
  },
  {
    ID: 13,
    userName: 'ngocbich678',
    fulName: 'Ngoc Bich',
    image: randomImg(),
    latestMessage: 'Gửi tài liệu cho mình với.',
    timeSend: 'hôm qua',
  },
  {
    ID: 14,
    userName: 'quanghuy456',
    fulName: 'Quang Huy',
    image: randomImg(),
    latestMessage: 'Khi nào mình gặp nhau nhỉ?',
    timeSend: '3 phút trước',
  },
  {
    ID: 15,
    userName: 'ngocmai890',
    fulName: 'Ngoc Mai',
    image: randomImg(),
    latestMessage: 'Bạn có xem phim không?',
    timeSend: 'hôm kia',
  },
  {
    ID: 16,
    userName: 'tuandung234',
    fulName: 'Tuan Dung',
    image: randomImg(),
    latestMessage: 'Đã có lịch thi chưa?',
    timeSend: '6 giờ trước',
  },
  {
    ID: 17,
    userName: 'thuha345',
    fulName: 'Thu Ha',
    image: randomImg(),
    latestMessage: 'Cảm ơn bạn!',
    timeSend: '1 phút trước',
  },
  {
    ID: 18,
    userName: 'baoanh678',
    fulName: 'Bao Anh',
    image: randomImg(),
    latestMessage: 'Hẹn gặp bạn sau.',
    timeSend: '5 ngày trước',
  },
  {
    ID: 19,
    userName: 'trungnguyen123',
    fulName: 'Trung Nguyen',
    image: randomImg(),
    latestMessage: 'Mai đi học không?',
    timeSend: 'hôm nay',
  },
  {
    ID: 20,
    userName: 'hoainam456',
    fulName: 'Hoai Nam',
    image: randomImg(),
    latestMessage: 'Nhớ đem tài liệu nhé.',
    timeSend: '2 giờ trước',
  },
  {
    ID: 21,
    userName: 'dieulinh567',
    fulName: 'Dieu Linh',
    image: randomImg(),
    latestMessage: 'Thời tiết hôm nay đẹp quá!',
    timeSend: '30 phút trước',
  },
  {
    ID: 22,
    userName: 'tuanlinh890',
    fulName: 'Tuan Linh',
    image: randomImg(),
    latestMessage: 'Có rảnh đi ăn tối không?',
    timeSend: '2 phút trước',
  },
  {
    ID: 23,
    userName: 'trucquynh123',
    fulName: 'Truc Quynh',
    image: randomImg(),
    latestMessage: 'Cho mình mượn sách nhé!',
    timeSend: 'hôm qua',
  },
  {
    ID: 24,
    userName: 'hongngoc345',
    fulName: 'Hong Ngoc',
    image: randomImg(),
    latestMessage: 'Hôm nay bận lắm không?',
    timeSend: '3 giờ trước',
  },
  {
    ID: 25,
    userName: 'nhatlam678',
    fulName: 'Nhat Lam',
    image: randomImg(),
    latestMessage: 'Mình thích bài nhạc này.',
    timeSend: '1 phút trước',
  },
  {
    ID: 26,
    userName: 'dailinh234',
    fulName: 'Dai Linh',
    image: randomImg(),
    latestMessage: 'Sắp đến rồi.',
    timeSend: '1 giờ trước',
  },
  {
    ID: 27,
    userName: 'thanhson456',
    fulName: 'Thanh Son',
    image: randomImg(),
    latestMessage: 'Bạn khỏe không?',
    timeSend: '8 giờ trước',
  },
  {
    ID: 28,
    userName: 'ngoctrai890',
    fulName: 'Ngoc Trai',
    image: randomImg(),
    latestMessage: 'Đi dạo không?',
    timeSend: 'hôm nay',
  },
  {
    ID: 29,
    userName: 'nhatquang123',
    fulName: 'Nhat Quang',
    image: randomImg(),
    latestMessage: 'Gọi lại cho mình nhé.',
    timeSend: '1 ngày trước',
  },
  {
    ID: 30,
    userName: 'truongson234',
    fulName: 'Truong Son',
    image: randomImg(),
    latestMessage: 'Nhớ giữ sức khỏe nhé.',
    timeSend: '2 ngày trước',
  },
  {
    ID: 31,
    userName: 'vanhoang567',
    fulName: 'Van Hoang',
    image: randomImg(),
    latestMessage: 'Chủ nhật này rảnh không?',
    timeSend: '5 phút trước',
  },
  {
    ID: 32,
    userName: 'hoanganh678',
    fulName: 'Hoang Anh',
    image: randomImg(),
    latestMessage: 'Cuối tuần vui vẻ nhé!',
    timeSend: '7 giờ trước',
  },
  {
    ID: 33,
    userName: 'thaotram345',
    fulName: 'Thao Tram',
    image: randomImg(),
    latestMessage: 'Gửi tài liệu cho mình nhé!',
    timeSend: '2 giờ trước',
  },
  {
    ID: 34,
    userName: 'ducminh567',
    fulName: 'Duc Minh',
    image: randomImg(),
    latestMessage: 'Mai đi làm sớm nhé.',
    timeSend: 'hôm nay',
  },
  {
    ID: 35,
    userName: 'khoapham678',
    fulName: 'Khoa Pham',
    image: randomImg(),
    latestMessage: 'Chào buổi sáng!',
    timeSend: '5 ngày trước',
  },
  {
    ID: 36,
    userName: 'ngochuyen234',
    fulName: 'Ngoc Huyen',
    image: randomImg(),
    latestMessage: 'Gặp lại sớm nhé!',
    timeSend: 'hôm qua',
  },
  {
    ID: 37,
    userName: 'anhquoc123',
    fulName: 'Anh Quoc',
    image: randomImg(),
    latestMessage: 'Có tin mới gì không?',
    timeSend: '10 phút trước',
  },
  {
    ID: 38,
    userName: 'lethinh456',
    fulName: 'Le Thinh',
    image: randomImg(),
    latestMessage: 'Chúc mừng sinh nhật!',
    timeSend: '1 giờ trước',
  },
  {
    ID: 39,
    userName: 'minhtam890',
    fulName: 'Minh Tam',
    image: randomImg(),
    latestMessage: 'Đi uống trà chiều không?',
    timeSend: '3 phút trước',
  },
  {
    ID: 40,
    userName: 'thanhmy567',
    fulName: 'Thanh My',
    image: randomImg(),
    latestMessage: 'Nhớ nhắn mình khi về nhé.',
    timeSend: 'hôm nay',
  },
  {
    ID: 41,
    userName: 'congson123',
    fulName: 'Cong Son',
    image: randomImg(),
    latestMessage: 'Bạn đang làm gì?',
    timeSend: '10 phút trước',
  },
  {
    ID: 42,
    userName: 'ngocduy234',
    fulName: 'Ngoc Duy',
    image: randomImg(),
    latestMessage: 'Hôm nay ăn gì?',
    timeSend: '1 ngày trước',
  },
  {
    ID: 43,
    userName: 'leduc456',
    fulName: 'Le Duc',
    image: randomImg(),
    latestMessage: 'Nhớ mình không?',
    timeSend: '4 giờ trước',
  },
  {
    ID: 44,
    userName: 'nguyenthanh789',
    fulName: 'Nguyen Thanh',
    image: randomImg(),
    latestMessage: 'Hẹn gặp sau nhé.',
    timeSend: '2 ngày trước',
  },
  {
    ID: 45,
    userName: 'kimngan567',
    fulName: 'Kim Ngan',
    image: randomImg(),
    latestMessage: 'Chúc ngủ ngon!',
    timeSend: 'hôm qua',
  },
  {
    ID: 46,
    userName: 'minhkhoi345',
    fulName: 'Minh Khoi',
    image: randomImg(),
    latestMessage: 'Đi dạo không?',
    timeSend: '10 phút trước',
  },
  {
    ID: 47,
    userName: 'quangbao567',
    fulName: 'Quang Bao',
    image: randomImg(),
    latestMessage: 'Rảnh đi cà phê nhé!',
    timeSend: '5 phút trước',
  },
  {
    ID: 48,
    userName: 'nguyenminh234',
    fulName: 'Nguyen Minh',
    image: randomImg(),
    latestMessage: 'Mai có thời gian không?',
    timeSend: 'hôm nay',
  },
  {
    ID: 49,
    userName: 'letrinh789',
    fulName: 'Le Trinh',
    image: randomImg(),
    latestMessage: 'Tối mai rảnh không?',
    timeSend: '2 giờ trước',
  },
  {
    ID: 50,
    userName: 'hoangtrung567',
    fulName: 'Hoang Trung',
    image: randomImg(),
    latestMessage: 'Lâu rồi không gặp!',
    timeSend: '1 ngày trước',
  }
];
