export default dataEnglishVocabulary = [
  { word: "Apple", meaning: "Quả táo, một loại trái cây có vị ngọt và giòn." },
  { word: "Beautiful", meaning: "Đẹp, có hình dáng dễ nhìn hoặc dễ chịu." },
  { word: "Run", meaning: "Chạy, di chuyển nhanh bằng chân." },
  { word: "House", meaning: "Ngôi nhà, nơi để ở." },
  { word: "Happy", meaning: "Vui vẻ, cảm thấy hài lòng, không lo âu." },
  { word: "Think", meaning: "Nghĩ, sử dụng trí óc để hiểu hoặc đưa ra quyết định." },
  { word: "Table", meaning: "Bàn, một vật dụng dùng để đặt đồ vật hoặc ăn uống." },
  { word: "Fast", meaning: "Nhanh, di chuyển với tốc độ cao." },
  { word: "Walk", meaning: "Đi bộ, di chuyển bằng cách dùng chân mà không chạy." },
  { word: "Cat", meaning: "Con mèo, một loài động vật nuôi phổ biến." },
  { word: "Smart", meaning: "Thông minh, có khả năng học hỏi hoặc giải quyết vấn đề nhanh chóng." },
  { word: "Eat", meaning: "Ăn, đưa thực phẩm vào cơ thể qua miệng." },
  { word: "Chair", meaning: "Ghế, một vật dụng dùng để ngồi." },
  { word: "Tall", meaning: "Cao, có chiều cao lớn." },
  { word: "Sleep", meaning: "Ngủ, trạng thái nghỉ ngơi của cơ thể." },
  { word: "Dog", meaning: "Con chó, một loài động vật nuôi phổ biến." },
  { word: "Cold", meaning: "Lạnh, có nhiệt độ thấp." },
  { word: "Dance", meaning: "Nhảy, di chuyển cơ thể theo nhạc." },
  { word: "Friend", meaning: "Bạn, người thân thiết, quen biết." },
  { word: "Big", meaning: "To, có kích thước lớn." },
  { word: "Study", meaning: "Học, nghiên cứu một chủ đề hoặc môn học." },
  { word: "Fast", meaning: "Nhanh, tốc độ cao." },
  { word: "Light", meaning: "Ánh sáng, vật phát ra ánh sáng hoặc sự nhẹ nhàng." },
  { word: "Hot", meaning: "Nóng, có nhiệt độ cao." },
  { word: "Read", meaning: "Đọc, nhìn vào và hiểu nội dung chữ viết." },
  { word: "Small", meaning: "Nhỏ, có kích thước bé." },
  { word: "Talk", meaning: "Nói, trao đổi thông tin bằng lời." },
  { word: "Winter", meaning: "Mùa đông, mùa lạnh trong năm." },
  { word: "Tall", meaning: "Cao, có chiều cao vượt trội." },
  { word: "Old", meaning: "Cũ, già, có tuổi thọ lớn." },
  { word: "Play", meaning: "Chơi, tham gia vào các hoạt động giải trí." },
  { word: "Quiet", meaning: "Yên tĩnh, không có tiếng động." },
  { word: "Strong", meaning: "Mạnh mẽ, có sức lực hoặc sức ảnh hưởng lớn." },
  { word: "Beautiful", meaning: "Đẹp, có vẻ ngoài thu hút." },
  { word: "Love", meaning: "Yêu, cảm giác thân thiết mạnh mẽ đối với ai đó." },
  { word: "Mountain", meaning: "Núi, một vùng đất cao lớn." },
  { word: "Summer", meaning: "Mùa hè, mùa ấm trong năm." },
  { word: "Light", meaning: "Sáng, không nặng." },
  { word: "Exciting", meaning: "Hào hứng, gây ra cảm giác thích thú." },
  { word: "Sing", meaning: "Hát, phát ra âm thanh có giai điệu." },
  { word: "Large", meaning: "Lớn, có kích thước lớn." },
  { word: "Play", meaning: "Chơi, tham gia hoạt động vui chơi." },
  { word: "Sad", meaning: "Buồn, cảm giác đau khổ hoặc không vui." },
  { word: "Window", meaning: "Cửa sổ, một phần của tường có thể mở ra để thông gió hoặc lấy ánh sáng." },
  { word: "Music", meaning: "Âm nhạc, các âm thanh hòa quyện tạo thành giai điệu." },
  { word: "Fast", meaning: "Nhanh chóng, có tốc độ cao." },
  { word: "Rain", meaning: "Mưa, nước rơi từ trên trời xuống." },
  { word: "Kind", meaning: "Tốt bụng, có lòng nhân ái." },
  { word: "Buy", meaning: "Mua, trao tiền để sở hữu một thứ gì đó." },
  { word: "Flower", meaning: "Hoa, một phần của cây, thường có màu sắc đẹp và mùi thơm." }
];
