let num = 50;
const randomImg = () => {
  num++;
  return "https://picsum.photos/" + num.toString();
};
export default dataGroups = [
  {
    groupID: 1,
    nameGroup: "Hội Học Tiếng Anh Vui Nhộn",
    imageGroup: randomImg(),
  },
  { groupID: 2, nameGroup: "Những Bé Thông Minh", imageGroup: randomImg() },
  { groupID: 3, nameGroup: "Đồng Bọn Học Tiếng Anh", imageGroup: randomImg() },
  { groupID: 4, nameGroup: "Team Bé Yêu Học Tập", imageGroup: randomImg() },
  { groupID: 5, nameGroup: "Nhóm Bé Học Giỏi", imageGroup: randomImg() },
  { groupID: 6, nameGroup: "Những Bé Yêu Tiếng Anh", imageGroup: randomImg() },
  { groupID: 7, nameGroup: "Hội Bé Học Vui", imageGroup: randomImg() },
  { groupID: 8, nameGroup: "Nhóm Bé Học Tiếng Anh", imageGroup: randomImg() },
  { groupID: 9, nameGroup: "Lớp Học Tiếng Anh", imageGroup: randomImg() },
  { groupID: 10, nameGroup: "Đội Bé Học Tốt", imageGroup: randomImg() },
  { groupID: 11, nameGroup: "Những Bé Yêu Sách", imageGroup: randomImg() },
  {
    groupID: 12,
    nameGroup: "Team Bé Dậy Sớm Học Tập",
    imageGroup: randomImg(),
  },
  { groupID: 13, nameGroup: "Nhóm Bé Phiêu Lưu", imageGroup: randomImg() },
  { groupID: 14, nameGroup: "Kẻ Yêu Học Tiếng Anh", imageGroup: randomImg() },
  { groupID: 15, nameGroup: "Team Bé Học Đêm", imageGroup: randomImg() },
  { groupID: 16, nameGroup: "Hội Bé Phá Vỡ Giới Hạn", imageGroup: randomImg() },
  { groupID: 17, nameGroup: "Nhóm Bé Học Thâu Đêm", imageGroup: randomImg() },
  {
    groupID: 18,
    nameGroup: "Đội Bé Tìm Kiếm Kiến Thức",
    imageGroup: randomImg(),
  },
  { groupID: 19, nameGroup: "Team Bé Thích Đánh Đố", imageGroup: randomImg() },
  {
    groupID: 20,
    nameGroup: "Những Bé Giải Cứu Thế Giới",
    imageGroup: randomImg(),
  },
  { groupID: 21, nameGroup: "Hội Bé Thích Hòa Bình", imageGroup: randomImg() },
  {
    groupID: 22,
    nameGroup: "Những Bé Khám Phá Bí Ẩn",
    imageGroup: randomImg(),
  },
  {
    groupID: 23,
    nameGroup: "Team Bé Kỹ Sư Tương Lai",
    imageGroup: randomImg(),
  },
  { groupID: 24, nameGroup: "Nhóm Bé Yêu Mèo", imageGroup: randomImg() },
  {
    groupID: 25,
    nameGroup: "Những Bé Bảo Vệ Thiên Nhiên",
    imageGroup: randomImg(),
  },
  {
    groupID: 26,
    nameGroup: "Hội Bé Khám Phá Công Nghệ",
    imageGroup: randomImg(),
  },
  {
    groupID: 27,
    nameGroup: "Team Bé Trí Tuệ Nhân Tạo",
    imageGroup: randomImg(),
  },
  { groupID: 28, nameGroup: "Những Bé Yêu Anime", imageGroup: randomImg() },
  { groupID: 29, nameGroup: "Team Bé Nghiện Coffee", imageGroup: randomImg() },
  {
    groupID: 30,
    nameGroup: "Nhóm Bé Phiêu Lưu Biển Xanh",
    imageGroup: randomImg(),
  },
  { groupID: 31, nameGroup: "Những Bé Phát Minh", imageGroup: randomImg() },
  { groupID: 32, nameGroup: "Team Bé Sống Ảo", imageGroup: randomImg() },
  { groupID: 33, nameGroup: "Hội Bé Đam Mê Coding", imageGroup: randomImg() },
  { groupID: 34, nameGroup: "Những Bé Làm Phim", imageGroup: randomImg() },
  { groupID: 35, nameGroup: "Đội Bé Luyện Game", imageGroup: randomImg() },
  { groupID: 36, nameGroup: "Team Bé Yêu Ẩm Thực", imageGroup: randomImg() },
  { groupID: 37, nameGroup: "Những Bé Hòa Bình", imageGroup: randomImg() },
  { groupID: 38, nameGroup: "Team Bé Lập Kế Hoạch", imageGroup: randomImg() },
  {
    groupID: 39,
    nameGroup: "Hội Bé Du Lịch Khám Phá",
    imageGroup: randomImg(),
  },
  { groupID: 40, nameGroup: "Đội Bé Chiến Binh", imageGroup: randomImg() },
  {
    groupID: 41,
    nameGroup: "Những Bé Phiêu Lưu Thế Giới",
    imageGroup: randomImg(),
  },
  { groupID: 42, nameGroup: "Hội Bé Mê Bóng Rổ", imageGroup: randomImg() },
  { groupID: 43, nameGroup: "Nhóm Bé Truyền Thông", imageGroup: randomImg() },
  {
    groupID: 44,
    nameGroup: "Team Bé Học Tập Và Phát Triển",
    imageGroup: randomImg(),
  },
  { groupID: 45, nameGroup: "Những Bé Cứu Thế", imageGroup: randomImg() },
  {
    groupID: 46,
    nameGroup: "Team Bé Khám Phá Khoa Học",
    imageGroup: randomImg(),
  },
  { groupID: 47, nameGroup: "Hội Bé Đam Mê Chụp Ảnh", imageGroup: randomImg() },
  { groupID: 48, nameGroup: "Những Bé Phá Băng", imageGroup: randomImg() },
  { groupID: 49, nameGroup: "Những Bé Mê Lịch Sử", imageGroup: randomImg() },
  { groupID: 50, nameGroup: "Team Bé Đọc Sách", imageGroup: randomImg() },
];
